# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy_server:
    name: Deploy server
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Replace variables
        run: |
              HISPANO_STATION_14_API_TOKEN=`tr -dc A-Za-z0-9 </dev/urandom | head -c 16 ; echo ''`
              sed -i 's@${HISPANO_STATION_14_API_TOKEN}@'"$HISPANO_STATION_14_API_TOKEN"'@' ./configuration/appsettings.yml
              sed -i 's@${DISCORD_ROUND_UPDATE_WEBHOOK}@'"$DISCORD_ROUND_UPDATE_WEBHOOK"'@' ./configuration/hispano_station14/config.toml
              sed -i 's@${DISCORD_AHELP_WEBHOOK}@'"$DISCORD_AHELP_WEBHOOK"'@' ./configuration/hispano_station14/config.toml
        env:
          DISCORD_ROUND_UPDATE_WEBHOOK: ${{ secrets.DISCORD_ROUND_UPDATE_WEBHOOK }}
          DISCORD_AHELP_WEBHOOK: ${{ secrets.DISCORD_AHELP_WEBHOOK }}
      - name: Run Docker Compose
        run: |
              docker compose down
              docker compose up -d
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
              
        
